### ISSUE TITLE
Arrow function breaks IE compatibility

### ISSUE THREAD

**Issue by pleunv** [developit/unfetch#100]
The following arrow function breaks compatibility with IE8+:

https://github.com/developit/unfetch/blob/1670b30b541ee9209c58653c550cf07489609cb9/src/index.mjs#L3

I don't know if this is something you are willing to fix, if not the following should probably be removed from the README:
> Supported: supports IE8+ (assuming Promise is polyfilled of course!)

**Comment by pleunv** [comment]
Mea culpa, it seems. We've been using `require('unfetch/polyfill');` for quite some time, but since the latest release this one defaults to the `mjs` build (or webpack 3 to the `module` field, at least).

**Comment by ikevanc** [comment]
I am getting the same error--How did you fix this?
Thanks!

**Comment by pleunv** [comment]
For now I'm just doing `require('unfetch/polyfill/index');`, since it otherwise defaults to `unfetch/polyfill/polyfill.mjs`. Still have to look into why webpack 3 seems to be preferring the `module` builds, despite that not being configured anywhere.
