### ISSUE TITLE
window not defined in web workers

### ISSUE THREAD

**Issue by piotrblasiak** [developit/unfetch#104]
The problem seems to be in browsers.js:

`module.exports = window.fetch || (window.fetch = require('unfetch').default || require('unfetch'));`

And I think this could be solved by replacing window with global?

**Comment by developit** [comment]
`global` is also not defined. We can use `self.

**Comment by eric-burel** [comment]
I hit the same issue when building from TypeScript, should I use a fork with this PR merged?
