### ISSUE TITLE
package.json module error

### ISSUE THREAD

**Issue by xutongbao** [developit/unfetch#114]
ok：
![unfetch](https://user-images.githubusercontent.com/29852563/57222466-45509f80-7035-11e9-80f2-250950c67520.png)

before：
![unfetch3](https://user-images.githubusercontent.com/29852563/57222580-ae381780-7035-11e9-9810-1a3604026f15.png)

error：
![unfetch2](https://user-images.githubusercontent.com/29852563/57222511-7cbf4c00-7035-11e9-9da5-d57c8ee48ecf.png)

**Comment by developit** [comment]
This was fixed in Next.js.
