### ISSUE TITLE
Use unfetch with service worker?

### ISSUE THREAD

**Issue by bschwartz757** [developit/unfetch#115]
Hello, just wondering if anyone has tried using unfetch with service workers. I'm wondering if requests made using unfetch are picked up by the service worker's fetch event listeners, or if there are things to be aware of there.

**Comment by simonbuerger** [comment]
Browsers that support service workers all support the fetch API natively, so if you're using unfetch as a polyfill it won't be an issue (as that will just use native fetch). Even if you're using it as a ponyfill I'm pretty sure service workers still intercept standard XHRs, but I've never tried it.

**Comment by developit** [comment]
Great answer @simonbuerger, couldn't have said it better myself.
