### ISSUE TITLE
NPM license is "none"

### ISSUE THREAD

**Issue by Vadorequest** [developit/unfetch#128]
There seems to be an issue with the license declared on NPM.

**Comment by AnonymousArthur** [comment]
> NPM license is "none"

License type `MIT` is declared in `package.json`. What do you mean?

**Comment by Vadorequest** [comment]
https://www.npmjs.com/package/isomorphic-unfetch

![image](https://user-images.githubusercontent.com/3807458/68659713-106b5b00-0538-11ea-91bd-47c4c9007f50.png)

**Comment by AnonymousArthur** [comment]
@Vadorequest Have a look on this: https://www.npmjs.com/package/unfetch

**Comment by styfle** [comment]
License is missing here: https://github.com/developit/unfetch/blob/master/packages/isomorphic-unfetch/package.json

@developit Can we assume this should be MIT?

**Comment by AnonymousArthur** [comment]
Ummm. OK, there's another package inside this package.

**Comment by developit** [comment]
Yes, it's MIT. Apologies!
