### ISSUE TITLE
pkg.module instead of jsnext:main?

### ISSUE THREAD

**Issue by ForsakenHarmony** [developit/unfetch#14]
https://github.com/rollup/rollup/wiki/jsnext:main
https://github.com/rollup/rollup/wiki/pkg.module

**Comment by developit** [comment]
Ah yup, meant to add both.

**Comment by ForsakenHarmony** [comment]
anything that doesn't support pkg.module?

**Comment by developit** [comment]
Not sure. Think it's easy enough just to rename instead of keeping both?

**Comment by tunnckoCore** [comment]
No. Better keep them both for some time.

**Comment by tunnckoCore** [comment]
I had some issue at `gibon` reported by some user of Webpack, that is using v2 release and some magical things are happening that it not loads the `pkg.module`. But anyway, they at least provide "CONFIGURATION"  object for that to allow you to say what is the "main" field of the package.

hence, why the hell we are going badge to configuration over convention? Never will like webpack. 2c, offtopic.
