### ISSUE TITLE
got url.replace is not a function

### ISSUE THREAD

**Issue by Edorka** [developit/unfetch#140]
I'm getting this error while doing a `yarn build` on a preact-cli project Complete message is
```
✖ ERROR TypeError: url.replace is not a function
    at /home/edorka/develop/nsp/node_modules/isomorphic-unfetch/index.js:3:36
```
Probably this is because code doesn't expect to get URL as an object this would be a quick fix:
```
module.exports = global.fetch = global.fetch || (
	typeof process=='undefined' ? (require('unfetch').default || require('unfetch')) : (function(url, opts) {
                const target = url.href ? url.href : url;
		return require('node-fetch')(target.replace(/^\/\//g,'https://'), opts);
	})
);
```

**Comment by developit** [comment]
Hiya! You're right, Unfetch isn't properly anticipating a URL object.

The fix is actually even smaller than checking .href - `URL.toString()` returns the URL string, so we can just do `url += ''`  to cast it to a string.
