### ISSUE TITLE
supabase V2.0.0 after update on Nuxt 3 problem cross-fetch  

### ISSUE THREAD

**Issue by SoftLaza** [developit/unfetch#157]
const supabase = createClient(url, key) 
will show error as the following 
`node_modules/cross-fetch/dist/browser-ponyfill.js?v=fdd8f129' does not provide an export named 'default' (at PostgrestBuilder.ts:1:8)`

anyone have solution for this

**Comment by developit** [comment]
If this is caused by unfetch at all (not sure if cross-fetch uses unfetch?), the default export behavior will have changed as of [unfetch 5.0.0](https://github.com/developit/unfetch/releases/tag/5.0.0).
