### ISSUE TITLE
Help, wanted! Country ntl-tel-input plugin is not working :(

### ISSUE THREAD

**Issue by Blondjuh** [developit/unfetch#166]
Hi there, as a newby on Github I'm looking for some community support. Recently integrated an ajax ntl-tel-input plugin that used to work - but is not working anymore. Is there anyone out there willing to help?
![image](https://user-images.githubusercontent.com/125469027/219040480-34897f92-4d95-4e83-8aba-a27de9b5de28.png)

It doesn't show the country flag dropdown anymore.
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
    </head>
    
    <script> 
            const phoneInputField = document.querySelector("#phone");
            const phoneInput = window.intlTelInput(phoneInputField, {
                utilsScript:
                "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js",
            }); 
    </script>

**Comment by developit** [comment]
Hi there. This has nothing to do with Unfetch. Please use https://stackoverflow.com/ for general web development questions.
