### ISSUE TITLE
allow ponyfill promise

### ISSUE THREAD

**Issue by cloudkite** [developit/unfetch#23]
Would be nice to be able to provide Promise for environments where we don't want to modify the window.

Would you be open to such a PR?

possible implementation
```
export function createFetch(Promise) {
   return function(url, options) {
      // XMLHttpRequest stuff here
  }
}

export default typeof fetch=='function' ? fetch : createFetch(Promise)
```

usage
```
import Promise from 'es6-promise'
import { createFetch } from 'unfetch'

const fetch = createFetch(Promise)
```

**Comment by tunnckoCore** [comment]
Maybe through `options` would be better and smaller approach. But yea, good catch.

**Comment by cloudkite** [comment]
@tunnckoCore yeah main concern here is introduction of some extra bytes. Adding Promise to options would mean we are deviating from standard fetch params though?

**Comment by developit** [comment]
I'm apprehensive of this in core due to the size, but I see why you might want it.  Do you have a specific environment/setup that needs it?

**Comment by cloudkite** [comment]
@developit its for a product that is embed into other websites, so cant modify window.

Im going to close as I'm happy to fork, please reopen if you think its worth addressing

**Comment by developit** [comment]
Ah, totally understandable.  One possible solution there would be a wrapper function that installs it only around `fetch()`:

```js
import unfetch from 'unfetch';
import Promise from 'es6-promise';

function fetch(url, opts) {
  let ret, prev = window.Promise;
  if (!window.Promise) window.Promise = Promise;
  ret = unfetch(url, opts);
  window.Promise = prev;
  return ret;
}
```
