### ISSUE TITLE
import "unfetch/polyfill" does not work

### ISSUE THREAD

**Issue by egauci** [developit/unfetch#24]
I see the polyfill code here on github, but it doesn't seem to be in npm. I get this sort of thing:

    Error: Cannot find module 'unfetch/polyfill' from '...'

**Comment by developit** [comment]
Sorry, release is lagging slightly behind documentation - that's a feature that is on master but has not yet been published to npm.  I'll update here when it is (in a few minutes hopefully!)

**Comment by developit** [comment]
This was released in [2.0.0](https://github.com/developit/unfetch/releases/tag/2.0.0).

**Comment by egauci** [comment]
Thanks!
