### ISSUE TITLE
Different behavior between native fetch and unfetch

### ISSUE THREAD

**Issue by suhaotian** [developit/unfetch#28]
native fetch:
![image](https://cloud.githubusercontent.com/assets/6512574/23347045/48a738b8-fcda-11e6-805f-fd17cf4ec193.png)

unfetch: 

![image](https://cloud.githubusercontent.com/assets/6512574/23347105/b83484e2-fcda-11e6-8ae7-f7d4aa842e24.png)

**Comment by developit** [comment]
Fixed and released as [2.1.1](https://github.com/developit/unfetch/releases/tag/2.1.1):

<img width="685" src="https://cloud.githubusercontent.com/assets/105127/23348413/d61cbd52-fc77-11e6-8018-6456a86d94cd.png">
