### ISSUE TITLE
Add caveats from Github fetch polyfill README to unfetch README

### ISSUE THREAD

**Issue by balloob** [developit/unfetch#29]
GitHub fetch polyfill [mentions a few caveats of using fetch](https://github.com/github/fetch#caveats).

I think that it would be nice to include them in your README too. It will help users new to the Fetch API prevent common mistakes. (I think "Handling HTTP error statuses" is the most important one)

I can open a PR to do this if you approve.

**Comment by tunnckoCore** [comment]
Kinda sounds good, but why not just directly redirect them to there? Why to moderate and duplicate some text :)

**Comment by developit** [comment]
Ooh, totally agreed - an explanation of transport errors vs connection errors would be great.

**Comment by balloob** [comment]
@developit aren't connection and transport errors the same? I would expect to distinguish between connection and response errors.

@tunnckoCore that is a good point but I think that just a link might be too easy to miss. The content shouldn't change much. @developit your call: link 🔗  or copy/paste(/adjust) 👨‍🎨

**Comment by tunnckoCore** [comment]
Yea, no problem, i'm okey with both. Just some self preferences, because i have some seo background hehe.

**Comment by developit** [comment]
whoop, @balloob yup I half-edited that message haha.
