### ISSUE TITLE
Difference between node-fetch?

### ISSUE THREAD

**Issue by eorroe** [developit/unfetch#35]
Hey just found this, and wondering what's the difference between [node-fetch](https://www.npmjs.com/package/node-fetch) ?

**Comment by tunnckoCore** [comment]
It is minimalistic and is part of the whole spec. If you use `isomorphic-unfetch` you can get `node-fetch`.

**Comment by developit** [comment]
Yup yup. Unfetch only works in the browser. The `isomorphic-unfetch` module @tunnkoCore mentioned actually just uses node-fetch if you import it under node.

**Comment by eorroe** [comment]
Oh, so this is like a polyfill? I don't develop for the web anymore but I used to just use it on [browsers that support it](http://caniuse.com/#feat=fetch)

**Comment by tunnckoCore** [comment]
Yea it is both ponyfill and polyfill.
