### ISSUE TITLE
Empty isomorphic-unfetch package

### ISSUE THREAD

**Issue by screendriver** [developit/unfetch#36]
I tried to write a unit test for my Browser application that does not run in the Browser but in my Bash with [ava](https://github.com/avajs/ava) or [tape](https://github.com/substack/tape). I'm using `unfetch` as a ponyfill by the way.

So my tests are crashing because it cannot find `XMLHttpRequest`. I looked at your source code here and found out that there is a `isomorphic-unfetch`. Great! So I can import `isomorphic-unfetch` in my app and it should run in the Browser **and** in my tests that run in a NodeJS environment.

Unfortunately the package on [npm](https://www.npmjs.com/package/isomorphic-unfetch) is empty.

![untitled](https://cloud.githubusercontent.com/assets/149248/24080508/532c8e06-0ca1-11e7-919b-f91876f00c08.png)

**Comment by tunnckoCore** [comment]
Good point. I was thinking the same thing when i seen that dir when it was created. Don't why I didn't report that ;d

**Comment by developit** [comment]
@screendriver @tunnckoCore published 1.0.0!
I had meant to last week but was unable to decide if `unfetch` and `node-fetch` would be better listed as `peerDependencies`.  For now I've just left them as normal dependencies.
