### ISSUE TITLE
README missing for isomorphic-unfetch

### ISSUE THREAD

**Issue by sedubois** [developit/unfetch#38]
<img width="639" alt="screen shot 2017-04-17 at 9 55 34" src="https://cloud.githubusercontent.com/assets/4217871/25081619/08d1c87a-2354-11e7-94b3-ec0111bf7c34.png">

**Comment by wuweiweiwu** [comment]
@developit it seems that the readme exists in the package. Would this issue be solved by running `npm publish` in that directory?

**Comment by developit** [comment]
yup.

**Comment by developit** [comment]
published! the readme is there now (and types!)
