### ISSUE TITLE
Missing API in README

### ISSUE THREAD

**Issue by vutran** [developit/unfetch#39]
`// Beginner friendly`

API section is missing in the README. This should either link to an external page like [this](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) or get documented.

**Comment by developit** [comment]
That seems like a good idea. Also would be a good spot to explain that the polyfill only covers `fetch()`, not `Response` or `Headers`.

**Comment by vutran** [comment]
Closing this :)
