### ISSUE TITLE
Reference to the SourceMap in dist

### ISSUE THREAD

**Issue by moonglum** [developit/unfetch#40]
The JS files in the `dist` contain a comment that references the SourceMap. When you `import` it and use something Webpack, there will not be the source map at the URL provided in the comment leading to a 404. Would it make sense to remove that line?

Thanks for the excellent package ❤️

**Comment by developit** [comment]
Hmm - Webpack deals with this automatically if you have `sourceMaps:true` enabled, or use `source-map-loader`.  Without that line, the sourcemap is ignored entirely.

**Comment by developit** [comment]
There are sourcemaps in dist. Perhaps this question was from an older update. Please re-open if its still an issue!
