### ISSUE TITLE
xml() method is invented

### ISSUE THREAD

**Issue by developit** [developit/unfetch#43]
Looks like I picked up baggage in my understanding of Fetch and invented an `.xml()` method on Response that doesn't actually exist.  We'll need to remove that since it's not spec compliant.

Originally noted here: tkh44/holen#3

**Comment by vesparny** [comment]
Here the specs

https://developer.mozilla.org/en-US/docs/Web/API/Response

**Comment by developit** [comment]
lovely! no mention of xml on that page, time to remove it :)
