### ISSUE TITLE
Issue with Safari Mobile on iOS 9

### ISSUE THREAD

**Issue by thangngoc89** [developit/unfetch#45]
I'm using preact-cli default set up and unfetch doesn't work there.
Device: iPhone 5S
Safari user-agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13D15 Safari/601.1`

I hope I can give more details but I'm using Ubuntu laptop and debugging it via [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy) so I have no access to console.log (or whatever).

Switch to `isomorphic-fetch` and it works again

**Comment by developit** [comment]
Interesting.  I also don't want to require unfetch - we should provide an option to specify alternative fetch and promise polyfills.  Is it failing entirely? Remember that unfetch does not polyfill `Request` or `Header` - just the `fetch()` function and its response values.

**Comment by thangngoc89** [comment]
@developit I can't tell. As I said above, I'm debugging this via [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy) so I can't see the actual error message. I wish I have a Mac around to properly debugging it.

My code is pretty straight-foward, no `Request` or `Headers` involve:

```
fetch(URL)
.then(res => res.json())
.then(doSomething())
```

And the search box on Preactjs.com is not working on this device too. (not sure if it's elevant)

**Comment by NekR** [comment]
Download hackintosh and install in VM. Boom, portable Mac 😉

**Comment by developit** [comment]
hmm - that's odd, the search box is just XHR (it's managed by Algolia's JS lib).

**Comment by developit** [comment]
Should be fixed in [unfetch@3.0.0 / isomorphic-unfetch@2.0.0](https://github.com/developit/unfetch/releases/tag/3.0.0).
