### ISSUE TITLE
Missing some globals

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [developit/unfetch#48]
The isomorphic-fetch library also polyfills the window.Response and window.Request constructors. Could unfetch support those instead of generating a response function inline?

The use case on our end is we extend the `.json()` method to first strip off an anti-XSS string.

**Comment by developit** [comment]
Hi @evan-scott-zocdoc - this isn't really something we can change about unfetch given the size limitation.  Unfetch only polyfills `window.fetch`, not any of the other related interfaces.  Given your use-case, I'd recommend sticking with `isomorphic-fetch` (internally `whatwg-fetch`).

Side note:  there are a lot of ways to avoid patching globals like you're doing. I'd be wary of patching like this unless absolutely necessary (eg: sandboxing 3rd party JS) - if the browser were ever to `Object.freeze(Response.prototype)`, your method for augmenting `.json()` would break irreparably.  

FWIW, here's a patch that would support both fetch and unfetch:

```js
let oldFetch = fetch;
fetch = function() {
  return oldFetch.apply(this, arguments).then(wrap)
}

function wrap(res) {
  res.json = () => res.text().then(stripXSSString).then(JSON.parse);
  return res;
}

function stripXSSString(json) {
  return json.replace(/^csrftoken=\w+,/gi, '');
}
```
