### ISSUE TITLE
How to hide console.error 

### ISSUE THREAD

**Issue by JeongTaekLim** [developit/unfetch#49]
I'm using `isomorphic-unfetch` with `next.js`
By the way, there is some 400 console.error on console in production.
`try`, `catch` not worked.
I have tried to find way to hide them on google but fail to get answer.
In production, I don't want to reveal my API server address in console.
Is there any way to hide them?

**Comment by charlike** [comment]
As you may simply review the source at this repository, you can see that we do nothing with the console, et al. So this issue probably should go to the `node-fetch`.
