### ISSUE TITLE
Convert fully to es6?

### ISSUE THREAD

**Issue by mikesherov** [developit/unfetch#6]
Seeing as this is already using es6, we can use destructuring and defaults to get even more byte savings. Would you accept a PR that does so?

**Comment by developit** [comment]
No, these increase the size of the output dramatically. The listed size is for transpiled output since that's what we pay for over the wire.

**Comment by mikesherov** [comment]
I suppose if you have es6, you have native fetch!

**Comment by developit** [comment]
Haha yeah that's so true.
