### ISSUE TITLE
Fail to handle header with blank value

### ISSUE THREAD

**Issue by zhuochen83** [developit/unfetch#60]
The regex at line 28 does not handle header with a blank value. 

Here is my test of the regex

var headers = "Server: \r\nmy-header: my-value\r\n";
headers.replace(/^(.*?):\s*([\s\S]*?)$/gm, (m, key, value) => {
  console.log(key + ' | ' + value);
})

Expecting 
"Server | "
"my-header | my-value"
Actual
"Server | my-header: my-value"

**Comment by developit** [comment]
Regex was missing a `?`! Good catch.
