### ISSUE TITLE
Publish isomorphic-unfetch with types

### ISSUE THREAD

**Issue by disintegrator** [developit/unfetch#64]
It seems the latest version of isomorphic-unfetch on npm does not yet have the recently added typescript definition. Would it be possible to publish a new release that includes this update or are there blockers that we can help resolve?

**Comment by jthegedus** [comment]
I am also available to help this over the line if needed :smiley:

**Comment by virzak** [comment]
+1. Really needed. Please and thank you!

**Comment by timpur** [comment]
+1

**Comment by resir014** [comment]
It seems that `index.d.ts` is not published to npm. I'm working on fixing it.

**Comment by resir014** [comment]
Done. It should be fixed when #70 is merged.

In the meantime, you can import it in your entry file like so:

```ts
// import isomorphic-unfetch as a polyfill
import 'isomorphic-unfetch'
```

**Comment by developit** [comment]
Bah, sorry folks I'm a terrible person.

**Comment by developit** [comment]
done!
