### ISSUE TITLE
Function Expected IE11 Error

### ISSUE THREAD

**Issue by yanv1991** [developit/unfetch#66]
In the client side when a request is executed in IE11 I got Function Expected in this return statement: 

`typeof process=='undefined' ? (require('unfetch').default || require('unfetch')) : (function(url, opts) {
		return require('node-fetch')(url.replace(/^\/\//g,'https://'), opts);
	})`

I'm using apollo client to make a graphql request, that this depends on a polyfill like isomorphic-unfetch

**Comment by developit** [comment]
I wonder if it's the empty `.bind()`?

**Comment by developit** [comment]
This should no longer be an issue in [4.0.0](https://github.com/developit/unfetch/releases/tag/4.0.0).
