### ISSUE TITLE
Does the module export the native version if it exists?

### ISSUE THREAD

**Issue by rauschma** [developit/unfetch#7]
Possibly mention in the readme: what happens in environment that have `fetch` if you import the polyfill from the module? Does it export the polyfill or the “native” version?

**Comment by developit** [comment]
Yup!

**Comment by rauschma** [comment]
Nice!

**Comment by jackfranklin** [comment]
@developit how does that happen, out of interest? I only ask as I was reading the source and couldn't spot how this happens :)

**Comment by developit** [comment]
Oh wow. I had it set up like that locally but must have reverted when I switched it to cjs! Will revert back :/

**Comment by developit** [comment]
Fwiw I wasn't sure the direction to go on this. There are two ways people polyfill that require different code:

```
if (!window.fetch) window.fetch = require('unfetch')

// Vs

import 'unfetch'
```

Maybe it would be worth exporting the former and then also exporting an `unfetch/polyfill` entry?

**Comment by rauschma** [comment]
How about:

```js
import 'unfetch/install'; // possibly installs polyfill globally
import unfetch from 'unfetch'; // doesn’t touch globals
```

**Comment by jackfranklin** [comment]
I'd call it `unfetch/polyfill` rather than `unfetch/install`, seems to be a more common pattern, but other than that I'd agree.

I'd still expect `unfetch/polyfill` to do nothing if `window.fetch` exists.

**Comment by developit** [comment]
so to summarize:

```js
import fetch from 'unfetch';   // will never return window.fetch

import 'unfetch/polyfill';   // installs globally if not already there, no exports
```

That'd be pretty easy to do - the current published version actually matches the explicit import from above, we'd just be adding a `polyfill.js` file:

```js
if (!window.fetch) window.fetch = require('.')
```

In terms of names, I'm ambivalent really.  I think I've seen `/polyfill` and `/register` used most commonly.

**Comment by jackfranklin** [comment]
@developit looks perfect 👍

**Comment by developit** [comment]
Awesome. Hopefully everyone else thinks so too 💃

**Comment by screendriver** [comment]
```js
import fetch from 'unfetch';
```

Looks like a ponyfill (not a polyfill) for me. So this would be good.

```js
import 'unfetch/register';
```

Looks like a polyfill for me. With this change I could modify my `webpack.config.js` from

```js
entry: ['whatwg-fetch', './src/index.js']
```

to

```js
entry: ['unfetch/register', './src/index.js']
```

and everything should still work.

**Comment by developit** [comment]
I'll do a twitter poll for the suffix, can't make a call on my own haha.

**Comment by rauschma** [comment]
@developit Ping me, I’ll retweet.

**Comment by developit** [comment]
Boom! Looks like we're rolling with `unfetch/polyfill`!

<img width="502" alt="screen shot 2017-02-22 at 8 43 15 pm" src="https://cloud.githubusercontent.com/assets/105127/23241182/ab6c87b2-f93f-11e6-9588-d23b2ab8ed18.png">

**Comment by screendriver** [comment]
Damn, I was sleeping 🛌 😂 

`unfetch/polyfill` looks good for me as well 😉

**Comment by developit** [comment]
Perfect :)  I've got it done, will publish today.
