### ISSUE TITLE
where to download the library?

### ISSUE THREAD

**Issue by pwFoo** [developit/unfetch#80]
I see a src directory, but where is a dist / lib directory with something like unfetch.js or unfetch.min.js?

**Comment by lucianopf** [comment]
@pwFoo that's usually not versioned, although it's not here at github if you do `npm i unfetch` and than import like `import fetch from 'unfetch'` you're basically requiring the file `dist/unfetch.js` [ref](https://github.com/developit/unfetch/blob/master/package.json#L5)

If you're actually looking to request this file without using npm itself you can use unpkg and use both urls:
`https://unpkg.com/unfetch` or `https://unpkg.com/unfetch@3.0.0/dist/unfetch.js` to a fixed version.

**Comment by developit** [comment]
Thanks for the awesome breakdown @lucianopf :)

Yup - for any library really, I'd recommend looking at unpkg.com when you want to download things rather than Github:

[https://unpkg.com/unfetch/](https://unpkg.com/unfetch/) (notice the trailing slash).

**Comment by developit** [comment]
looks like it's already explained in the Readme, so I'll close this one out.
