### ISSUE TITLE
Isomorphic-unfetch typescript definition error

### ISSUE THREAD

**Issue by deptno** [developit/unfetch#87]
Hi.

https://github.com/developit/unfetch/blob/master/packages/isomorphic-unfetch/index.js#L1

code uses `module.exports`, but definition is using `export default`, I think it should be `export =` in  https://github.com/developit/unfetch/blob/master/packages/isomorphic-unfetch/index.d.ts#L17

and use with `import * as fetch from 'isomorphic-unfetch'

### Related issue
- https://github.com/developit/unfetch/issues/82

**Comment by developit** [comment]
Definitely - would you be up for PR'ing that change?

**Comment by deptno** [comment]
https://github.com/developit/unfetch/pull/89
