### ISSUE TITLE
[question] how to replace whatwg-fetch with unfetch using webpack?

### ISSUE THREAD

**Issue by tuananh** [developit/unfetch#88]
I use a third party lib that has `whatwg-fetch` as dependency.

can i replace that with `unfetch` using webpack?

i tried `config.resolve.alias` but it doesn't seem to work.

**Comment by simonbuerger** [comment]
I haven't actually tried this, but whatwg-fetch is a polyfill, so did you use alias `{ 'whatwg-fetch': 'unfetch/polyfill' }`?

**Comment by tuananh** [comment]
@simonbuerger that's what i did but then [pwa](https://github.com/lukeed/pwa) or webpack is throwing some weird error

**Comment by tuananh** [comment]
Closing, issue seems to be related to pwa
