### ISSUE TITLE
Support ponyfilled Promise

### ISSUE THREAD

**Issue by Aaronius** [developit/unfetch#95]
Thanks for the great work on this library. I work on a tag management system that pushes code out to customers' websites. We avoid setting globals so that there are no unintended consequences on their websites and, in order to do so, we use a promise ponyfill within our library. We'd like to start using Unfetch, but it assumes that the promise will be set as a global, which for our case can't be the case when we need to use our ponyfill. We're willing to modify Unfetch for our needs to allow us to specify the promise implementation it should use, but I could see this being useful for other Unfetch consumers as well. Would there be any interest in adding support for this?

**Comment by styfle** [comment]
I think the ponyfill was added in [v4.0.0](https://github.com/developit/unfetch/releases/tag/4.0.0)

**Comment by Aaronius** [comment]
I think there may be understanding. While I can use unfetch as a ponyfill based on what was released in v4.0.0, I still need unfetch to use a ponyfilled promise implementation.

**Comment by simonbuerger** [comment]
How are you bundling? If you're using webpack you should be able to use imports-loader?

**Comment by Aaronius** [comment]
We're using Rollup. My first attempt was going to be something like that if Unfetch didn't support it "natively".

**Comment by simonbuerger** [comment]
https://github.com/rollup/rollup-plugin-inject/blob/master/README.md ?

**Comment by Aaronius** [comment]
Yeah, I was having problems with that plugin, but haven't had time to dig into it deeply. In any case, I realize it's possible to handle it on the bundling side so if that's the answer then I'm okay with it. Just let me know and I'll close the issue.

**Comment by bytestream** [comment]
@simonbuerger would you mind providing an example using webpack imports-loader? I just keep getting `require is not defined` when it adds `var Promise = require('core-js/fn/promise');` to unfetch

**Comment by developit** [comment]
@bytestream imports-loader should work:

```js
const unfetch = require("imports-loader?Promise=promise-polyfill!unfetch");
```
